# ============================================================
#  InmoVista — Configuración de Base de Datos
#  db.properties  →  colocar en /WEB-INF/
# ============================================================

# ── ENTORNO ACTIVO: "local" o "cloud" ──────────────────────
db.active=cloud

# ── LOCAL (MySQL instalado en tu máquina) ──────────────────
local.driver=com.mysql.cj.jdbc.Driver
local.url=jdbc:mysql://localhost:3306/inmovista_db?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
local.user=root
local.password=tu_password_local
local.database=inmovista_db

# ── CLOUD (Clever Cloud MySQL) ──────────────────────────────
cloud.driver=com.mysql.cj.jdbc.Driver
cloud.url=jdbc:mysql://by8sl4ll3wmw8dex7qzt-mysql.services.clever-cloud.com:3306/by8sl4ll3wmw8dex7qzt?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
cloud.user=uf7uiezwq3tjedqa
cloud.password=9vpBUmwZ8xqi4kP8FmXe
cloud.database=by8sl4ll3wmw8dex7qzt

# ── POOL DE CONEXIONES ─────────────────────────────────────
pool.maxConnections=10
pool.minConnections=2
pool.connectionTimeout=30000
pool.idleTimeout=600000
